PAreport = function(prescription=prescription,mine_data=mine_data,net=net,database=database,fields=c('assess','influence'),mechanism=FALSE,literature=FALSE,drug_Name=drug_name,TopDisease=5,TopDrug=10,tS0.9=0.03,min_yao=8,threshold_leastYao=10,onlyHerb=FALSE,Drug_pair_analysis=FALSE,local=TRUE,Report=TRUE,interact_analysis=TRUE,overlap_analysis=TRUE,p_analysis=TRUE,drug_NameCheck=FALSE,filetype='dbf',
                  Table1_rt=TRUE,Table1_n=10,
                  Table1_1_rt=TRUE,Table1_1_n=10,
                  Table1_2_rt=TRUE,Table1_2_n=10,
                  Table1_3_rt=TRUE,Table1_3_n=10,
                  Table1_4_rt=TRUE,Table1_4_n=10,
                  Table1_5_rt=TRUE,Table1_5_n=10,
                  Table1_6_rt=TRUE,Table1_6_n=10,
                  Table1_7_rt=TRUE,Table1_7_n=10,
				          Table1_8_rt=TRUE,Table1_8_n=10,
                  Table2_rt=TRUE,Table2_n=10,
                  Table2_1_rt=TRUE,Table2_1_n=10,
                  Table2_2_rt=TRUE,Table2_2_n=10,
                  Table2_3_rt=TRUE,Table2_3_n=10,
                  Table3_1_rt=TRUE,Table3_1_n=10,
                  Table3_2_rt=TRUE,Table3_2_n=10,
                  Table3_3_rt=TRUE,Table3_3_n=10,
                  Table3_4_rt=TRUE,Table3_4_n=10,
                  Table3_5_rt=TRUE,Table3_5_n=10,
                  Table3_6_rt=TRUE,Table3_6_n=10,
				          Table3_7_rt=TRUE,Table3_7_n=10,
				          Table3_8_rt=TRUE,Table3_8_n=10,
                  FTable1_rt=TRUE,FTable1_n=10,x64=TRUE){
require(compiler)

#fcPA=suppressWarnings(cmpfun(PA))
#fcreport=suppressWarnings(cmpfun(report))
sa=PA(prescription=prescription,mine_data=mine_data,net=net,database=database,fields=c('assess','influence'),mechanism=mechanism,literature=literature,drug_Name=drug_Name,TopDisease=TopDisease,TopDrug=TopDrug,tS0.9=tS0.9,min_yao=min_yao,threshold_leastYao=threshold_leastYao,onlyHerb=onlyHerb,Drug_pair_analysis=Drug_pair_analysis,local=local,interact_analysis=interact_analysis,overlap_analysis=overlap_analysis,p_analysis=p_analysis,drug_NameCheck=drug_NameCheck,filetype=filetype)
if (Report){
  report(sa,Table1_rt=Table1_rt,Table1_n=Table1_n,
         Table1_1_rt=Table1_1_rt,Table1_1_n=Table1_1_n,
         Table1_2_rt=Table1_2_rt,Table1_2_n=Table1_2_n,
         Table1_3_rt=Table1_3_rt,Table1_3_n=Table1_3_n,
         Table1_4_rt=Table1_4_rt,Table1_4_n=Table1_4_n,
         Table1_5_rt=Table1_5_rt,Table1_5_n=Table1_5_n,
         Table1_6_rt=Table1_6_rt,Table1_6_n=Table1_6_n,
         Table1_7_rt=Table1_7_rt,Table1_7_n=Table1_7_n,
		     Table1_8_rt=Table1_8_rt,Table1_8_n=Table1_8_n,
         Table2_rt=Table2_rt,Table2_n=Table2_n,
         Table2_1_rt=Table2_1_rt,Table2_1_n=Table2_1_n,
         Table2_2_rt=Table2_2_rt,Table2_2_n=Table2_2_n,
         Table2_3_rt=Table2_3_rt,Table2_3_n=Table2_3_n,
         Table3_1_rt=Table3_1_rt,Table3_1_n=Table3_1_n,
         Table3_2_rt=Table3_2_rt,Table3_2_n=Table3_2_n,
         Table3_3_rt=Table3_3_rt,Table3_3_n=Table3_3_n,
         Table3_4_rt=Table3_4_rt,Table3_4_n=Table3_4_n,
         Table3_5_rt=Table3_5_rt,Table3_5_n=Table3_5_n,
         Table3_6_rt=Table3_6_rt,Table3_6_n=Table3_6_n,
		     Table3_7_rt=Table3_7_rt,Table3_7_n=Table3_7_n,
		     Table3_8_rt=Table3_8_rt,Table3_8_n=Table3_8_n,
         FTable1_rt=FTable1_rt,FTable1_n=FTable1_n,x64=x64)
  return(sa)
}else{
  return(sa)
}
}

